server/account/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns('account.views',
  url(r'^sign-up/$', 'sign_up', name="sign-up"),
  url(r'^sign-up-success/$', 'sign_up_success', name="sign-up-success"),
  
  url(r'^brain-dead/$', 'password_reset', name="password-reset"),
  url(r'^brain-dead/sent/$', 'password_reset_sent', name="password-reset-sent"),
  url(r'^brain-dead/final/$', 'password_reset_final', name="password-reset-final"),
  url(r'^brain-dead/not-anymore/$', 'password_reset_success', name="password-reset-success"),
  
  url(r'^email-verify/$', 'email_verify', name="email-verify"),
)

server/editor/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns('editor.views',
  url(r'^login/$', 'login_view'),
  url(r'^logout/(.*)$', 'logout_view'),
  
  url(r'^generate-api-key$', 'gen_api_key'),
  url(r'^ekey$', 'ekey'),
  url(r'^get-ekey$', 'get_ekey'),
  
  url(r'^error$', 'report_error'),
  
  url(r'^credits$', 'credits'),
)

server/members/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns('members.views',
  url(r'^$', 'members_home', name="home"),
  url(r'^login/$', 'members_login', name="login"),
  url(r'^cancel/$', 'members_cancel', name="cancel"),
  url(r'^purchase/(\S+)/$', 'purchase', name="purchase"),
  url(r'^charge/(\S+)/$', 'charge', name="charge"),
  url(r'^edit-name/$', 'edit_name', name="edit-name"),
  url(r'^paypal-success/$', 'paypal_success', name="paypal-success"),
  url(r'^support/$', 'support', name="support"),
)

server/ndrive/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('ndrive.views',
  url(r'^grappelli/', include('grappelli.urls')),
  url(r'^admin/', include(admin.site.urls)),
  
  url(r'^editor/', include('editor.urls', namespace='editor', app_name='editor')),
  url(r'^account/', include('account.urls', namespace='account', app_name='account')),
  url(r'^members/', include('members.urls', namespace='members', app_name='members')),
  
  url(r'^paypal-processing/', include('paypal.standard.ipn.urls')),
  
  url(r'^$', 'home'),
  url(r'^favicon.ico$', 'favicon'),
  url(r'^favicon.png$', 'favicon'),
  
  url(r'^help/$', 'page_view', name="help", kwargs={'template': 'pages/help.html'}),
  url(r'^help/neutron-beam-setup$', 'page_view', name="help-nbeam-setup", kwargs={'template': 'pages/help-nbeam-setup.html'}),
  
  url(r'^view-(\d+)$', 'gdrive_webview'),
  url(r'^edit$', 'gdrive_webview'),
)

server/account/models.py
import urllib
import datetime
from importlib import import_module
from collections import OrderedDict

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager

from ndrive.utils.lib import cached_method
from ndrive.utils.email import send_mail

import jwt

from paypal.standard.ipn.signals import subscription_signup

SESSION_ENGINE = import_module(settings.SESSION_ENGINE)

class User (AbstractBaseUser, PermissionsMixin):
  verified_email = models.EmailField('verified email address', null=True, blank=True)
  verified = models.BooleanField(default=False)
  newsletter = models.BooleanField('Subscribe to Newsletter', default=False)
  
  first_name = models.CharField('first name', max_length=30, blank=True)
  last_name = models.CharField('last name', max_length=30, blank=True)
  
  username = models.CharField('Username', max_length=30, unique=True,
        help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.',
        validators=[
          validators.RegexValidator(r'^[\w.@+-]+$', 'Enter a valid username.', 'invalid')
        ])
  email = models.EmailField('E-Mail', unique=True)
  
  is_staff = models.BooleanField('staff status', default=False,
    help_text='Designates whether the user can log into this admin site.')
  is_active = models.BooleanField('active', default=True,
    help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')
  date_joined = models.DateTimeField('date joined', default=timezone.now)
  
  USERNAME_FIELD = 'username'
  REQUIRED_FIELDS = ['email']
  
  objects = UserManager()
  
  def __unicode__ (self):
    return self.username
    
  def get_short_name (self):
    return self.username
    
  @staticmethod
  def autocomplete_search_fields():
    return ("id__iexact", "username__icontains", "email__icontains", "first_name__icontains", "last_name__icontains")
    
  def chrome_token (self, session):
    return jwt.encode({
      'session': session.session_key,
      'exp': datetime.datetime(2030, 1, 1)
    }, settings.SECRET_KEY)
    
  @staticmethod
  def get_session (token):
    payload = jwt.decode(token, settings.SECRET_KEY, verify_expiration=False)
    return SESSION_ENGINE.SessionStore(payload['session'])
    
  def send_verify (self, request):
    if self.email != self.verified_email:
      EmailVerify.new_verify(self, request)
      
  def send_pwreset (self, request):
    EmailVerify.new_verify(self, request, True)
    
  @cached_method
  def subscription (self):
    try:
      return self.subscription_set.filter(expires__gte=timezone.now())[0]
      
    except:
      return None
      
class EmailVerify (models.Model):
  user = models.ForeignKey(User)
  email = models.EmailField()
  used = models.BooleanField(default=False)
  reset = models.BooleanField(default=False)
  
  created = models.DateTimeField(default=timezone.now)
  
  class Meta:
    verbose_name = 'E-Mail Verify'
    verbose_name_plural = 'E-Mail Verifies'
    
  def __unicode__ (self):
    return self.email
    
  def qs (self):
    return '?token={}&email={}'.format(self.token(), urllib.quote(self.email))
    
  @cached_method
  def token (self):
    return jwt.encode({'id': self.id, 'created': unicode(self.created)}, settings.SECRET_KEY)
    
  @staticmethod
  def new_verify (user, request, reset=False):
    verify = EmailVerify(user=user, email=user.email, reset=reset)
    verify.save()
    
    context = {'verify': verify, 'request': request}
    if reset:
      tpl = 'account/email.password-reset'
      send_mail('Password Reset - {site_name}', [verify.email], tpl, context)
      
    else:
      tpl = 'account/email.verify'
      send_mail('Please Verify Your E-Mail - {site_name}', [verify.email], tpl, context)
      
    return verify
    
  @staticmethod
  def verify_token (token, email, age=10, reset=False):
    payload = jwt.decode(token, settings.SECRET_KEY)
    
    old = timezone.now() - datetime.timedelta(days=age)
    verify = EmailVerify.objects.get(
      id=payload['id'],
      email=email,
      created__gte=old,
      used=False,
      reset=reset,
    )
    
    if not reset:
      verify.used = True
      verify.save()
      
    return verify
    
SUBS_TYPES = [
  ('initiate', 'Initiate'),
  ('padawan', 'Padawan'),
  ('knight', 'Knight'),
  ('master', 'Master'),
  ('grand-master', 'Grand Master'),
]

SUBSCRIPTIONS = OrderedDict([
  ('initiate', {
    'cost': 2500,
    'name': 'Initiate'
  }),
  ('padawan', {
    'cost': 5000,
    'name': 'Padawan'
  }),
  ('knight', {
    'cost': 9900,
    'name': 'Knight'
  }),
  ('master', {
    'cost': 30000,
    'name': 'Master'
  }),
  ('grand-master', {
    'cost': 50000,
    'name': 'Grand Master'
  }),
])

if settings.DEBUG:
  SUBSCRIPTIONS['special'] = {'cost': 200, 'name': 'Special'}
  SUBS_TYPES.append(('special', 'Special'))
  
class Subscription (models.Model):
  user = models.ForeignKey(User)
  name = models.CharField('Display Name for Credits', max_length=30)
  stype = models.CharField('Subscription Type', max_length=20, choices=SUBS_TYPES)
  
  stripe_id = models.CharField(max_length=255, blank=True, null=True)
  stripe_subs = models.CharField(max_length=255, blank=True, null=True)
  
  paypal_id = models.CharField(max_length=255, blank=True, null=True)
  paypal_subs = models.CharField(max_length=255, blank=True, null=True)
  
  expires = models.DateTimeField()
  cancelled = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)
  
  class Meta:
    ordering = ('-expires',)
    
  def __unicode__ (self):
    return self.user.username
    
  def payment_type (self):
    if self.stripe_id:
      return 'Stripe'
      
    return 'PayPal'
    
def paypal_subs_created (sender, **kwargs):
  user = User.objects.get(id=sender.custom)
  
  subs = Subscription(
    user = user,
    name = user.username,
    stype = sender.item_number,
    expires = timezone.now() + datetime.timedelta(days=365),
    paypal_id = sender.payer_email,
    paypal_subs = sender.subscr_id,
  )
  subs.save()
  
subscription_signup.connect(paypal_subs_created)

server/members/models.py
from django.db import models

class Feature (models.Model):
  creator = models.ForeignKey('account.User')
  
  title = models.CharField(max_length=120)
  desc = models.TextField('Description')
  
  approved = models.BooleanField(default=False)
  closed = models.BooleanField(default=False)
  
  votes = models.IntegerField(default=0)
  
  created = models.DateTimeField(auto_now_add=True)
  
  def __unicode__ (self):
    return self.title
    

server/members/forms.py
from django import forms

class NameForm (forms.Form):
  name = forms.CharField(max_length=30)
  
class SupportForm (forms.Form):
  email = forms.EmailField()
  request = forms.CharField(max_length=1500, widget=forms.Textarea)
  

server/members/views.py
import datetime

from django import http
from django.conf import settings
from django.template.response import TemplateResponse
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.utils import timezone

from account.models import Subscription, SUBSCRIPTIONS
from account.auth import login_required
from editor.forms import LoginForm
from members.forms import NameForm, SupportForm
from ndrive.utils.email import send_mail

from paypal.standard.forms import PayPalPaymentsForm

import stripe
stripe.api_key = settings.STRIPE_SECRET

def members_home (request):
  subs = None
  if request.user.is_authenticated():
    subs = request.user.subscription()
    
  context = {
    'subscriptions': SUBSCRIPTIONS,
    'subscription': subs
  }
  return TemplateResponse(request, 'members/home.html', context)
  
def members_login (request):
  cont = request.GET.get('cont', '')
  init = {'app_id': 'none'}
  if cont:
    init['cont'] = cont
    
  form = LoginForm(request.POST or None, initial=init)
  if request.POST:
    if form.is_valid():
      login(request, form.cleaned_data['user'])
      return http.HttpResponseRedirect(form.cleaned_data['cont'])
      
  context = {
    'form': form,
  }
  return TemplateResponse(request, 'members/login.html', context)
  
def paypal_button (request, key, subs):
  base = 'http'
  if request.is_secure():
    base += 's://'
    
  else:
    base += '://'
    
  base += request.get_host()
  
  paypal_dict = {
    "cmd": "_xclick-subscriptions",
    "business": settings.PAYPAL_RECEIVER_EMAIL,
    "a3": "{:.2f}".format(subs['cost'] / 100),
    "p3": 1,
    "t3": "Y",
    "src": "1",
    "sra": "1",
    "lc": "US",
    "currency_code": "USD",
    "bn": "PP-SubscriptionsBF:btn_subscribeCC_LG.gif:NonHosted",
    "no_note": "1",
    "no_shipping": "1",
    "item_name": "{} {} Membership".format(settings.SITE_NAME, subs['name']),
    "item_number": key,
    "custom": "{}".format(request.user.id),
    "notify_url": base + reverse('paypal-ipn'),
    "return_url": base + reverse('members:paypal-success'),
    "cancel_return": base + reverse('members:home'),
  }
  
  return PayPalPaymentsForm(initial=paypal_dict, button_type="subscribe")
  
@login_required
def purchase (request, level):
  try:
    subs = SUBSCRIPTIONS[level]
    
  except:
    raise http.Http404
    
  context = {
    'key': level,
    'level': subs,
    'paypal_button': paypal_button(request, level, subs)
  }
  return TemplateResponse(request, 'members/purchase.html', context)
  
@login_required
def charge (request, level):
  token = request.POST['stripeToken']
  email = request.POST['stripeEmail']
  
  customer = stripe.Customer.create(
    card=token,
    plan=level,
    email=email,
  )
  
  subs = Subscription(
    user = request.user,
    name = request.user.username,
    stype = level,
    stripe_id = customer['id'],
    stripe_subs = customer['subscriptions']['data'][0]['id'],
    expires = timezone.now() + datetime.timedelta(days=365),
  )
  subs.save()
  
  return http.HttpResponseRedirect(reverse('members:home'))
  
@login_required
def members_cancel (request):
  subs = request.user.subscription()
  
  customer = stripe.Customer.retrieve(subs.stripe_id)
  customer.subscriptions.retrieve(subs.stripe_subs).delete()
  
  subs.cancelled = True
  subs.save()
  
  return http.HttpResponseRedirect(reverse('members:home'))
  
@login_required
def edit_name (request):
  subs = request.user.subscription()
  form = NameForm(request.POST or None, initial={'name': subs.name})
  
  if request.POST:
    if form.is_valid():
      subs.name = form.cleaned_data['name']
      subs.save()
      return http.HttpResponseRedirect(reverse('members:home'))
      
  context = {
    'form': form,
    'action': 'Save',
    'icon': 'caret-square-o-right',
  }
  return TemplateResponse(request, 'members/edit-name.html', context)
  
def paypal_success (request):
  context = {}
  return TemplateResponse(request, 'members/paypal-success.html', context)
  
@login_required
def support (request):
  form = SupportForm(request.POST or None, initial={'email': request.user.email})
  
  if request.POST:
    if form.is_valid():
      send_mail(
        'Support Request - ' + form.cleaned_data['email'],
        [settings.MEMBER_EMAIL],
        'members/support-request.email',
        {'request': request, 'email': form.cleaned_data['email'], 'info': form.cleaned_data['request']}
      )
      return TemplateResponse(request, 'members/support-success.html', {})
      
  context = {
    'form': form,
    'action': 'Submit',
    'icon': 'caret-square-o-right',
  }
  return TemplateResponse(request, 'members/support.html', context)
  

server/ndrive/views.py
from django import http
from django.conf import settings
from django.template.response import TemplateResponse

def home (request):
  context = {}
  return TemplateResponse(request, 'pages/home.html', context)
  
def favicon (request):
  return http.HttpResponseRedirect('/static/favicon.png')
  
def gdrive_webview (request, index=None):
  if index is None:
    index = request.GET.get('view', '0')
    
  tpl = 'gdrive_webview.html'
  if index == 'test':
    tpl = 'test.html'
    
  return TemplateResponse(
    request,
    tpl,
    {
      'index': index,
      'google_key': settings.GOOGLE_KEY,
      'google_client_id': settings.GOOGLE_CLIENT_ID,
      'google_app_id': settings.GOOGLE_APP_ID,
    }
  )
  
def page_view (request, template=None):
  return TemplateResponse(request, template, {})
  

server/ndrive/templates/members/edit-name.html
{% extends "base.html" %}
{% block title %}Edit Display Name{% endblock %}
{% block content %}
<div layout="horizontal" layout-align="center">
  <md-card ng-controller="FormController">
    <h2>Edit Display Name</h2>
    {% include "form.html" %}
  </md-card>
</div>
{% endblock content %}
{% block js %}
{{ block.super }}

<script>
  {% include "form-controller.js" %}
</script>
{% endblock js %}

server/ndrive/templates/members/home.html
{% extends "base.html" %}{% load static ndrive %}
{% block title %}Members{% endblock %}
{% block content %}
<div id="MembersPage">
  <div layout="horizontal" layout-align="center">
    <md-card class="page">
      {% if request.user.is_authenticated %}
      <h2>Neutron Drive Membership - {{ request.user.username }}</h2>
      {% if subscription %}
      <h3>Welcome Jedi {{ subscription.get_stype_display }}</h3>
      <p>
        Membership Renewal/Expiration: {{ subscription.expires|date:"m/d/Y" }}
        <br><br>
        <strong>Display Name for Credits:</strong><br>
        {{ subscription.name }}&nbsp; -&nbsp; 
        <a href="{% url "members:edit-name" %}">Edit</a>
        <br><br>
        {% if subscription.cancelled %}
        <strong>Membership Cancelled</strong>
        {% else %}
        {% if subscription.stripe_id and not subscription.cancelled %}
        <a href="{% url "members:cancel" %}" onclick="return confirm('Are you sure you want to cancel your subscription?')">Cancel Membership Renewal &raquo;</a>
        {% elif subscription.paypal_id and not subscription.cancelled %}
        <a href="https://www.paypal.com/us/cgi-bin/webscr?cmd=_profile-recurring-payments&encrypted_profile_id={{ subscription.paypal_subs }}" target="_blank">PayPal Subscription (you can cancel here) &raquo;</a>
        {% endif %}
        {% endif %}
      </p>
      <hr>
      {% if subscription %}
      <p>
        <md-button href="{% url "members:support" %}"  class="md-button-raised md-button-colored">
          Submit A Support Request &raquo;
        </md-button>
      </p>
      {% endif %}
      <p>
        <strong>Coming soon!</strong> Look for feature submission and voting soon.
      </p>
      {% else %}
      <p>
        Membership gives you access to elevated tech support and the ability to 
        vote on and suggest new features for Neutron Drive. You'll also be listed
        in the Neutron Drive credits.
      </p>
      <h3>Choose A Level</h3>
      <ul>
        {% for key, subs in subscriptions.items %}
        <li>
          <strong><a href="{% url 'members:purchase' key %}">{{ subs.name }}, ${{ subs.cost|dollars }}/year</a></strong>
          <br><br>
        </li>
        {% endfor %}
      </ul>
      {% endif %}
      {% else %}
      <h2>Neutron Drive Membership</h2>
      <p>
        Membership gives you access to elevated tech support and the ability to 
        vote on and suggest new features for Neutron Drive. You'll also be listed
        in the Neutron Drive credits.
      </p>
      <hr>
      <h2>Become A Member Today</h2>
      <p>
        <md-button href="{% url "account:sign-up" %}?cont={% url "members:home" %}" class="md-button-raised md-button-colored">
          Create An Account &raquo;
        </md-button>
        <br><br><br>
        Already have an account?<br><br>
        <md-button href="{% url "members:login" %}?cont={% url "members:home" %}" class="md-button-raised md-button-colored">
          Sign In &raquo;
        </md-button>
      </p>
      {% endif %}
    </md-card>
    
  </div>
</div>
{% endblock content %}

server/ndrive/templates/members/login.html
{% extends "base.html" %}{% load ndrive %}
{% block title %}Login{% endblock %}
{% block content %}
<div layout="horizontal" layout-align="center">
  <md-card ng-controller="LoginController">
    <div class="pull-right buttons">
      <md-button {% target %} href="{% url "account:sign-up" %}?cont={{ form.cont.value }}" class="highlight">
        <i class="fa fa-pencil-square-o"></i> Sign Up
      </md-button>
      <md-button target="_blank" href="{% url "account:password-reset" %}" class="highlight">
        <i class="fa fa-question-circle"></i> Forgot My Password
      </md-button>
    </div>
    <h2>Login</h2>
    <form action="{{ request.path }}" method="post" ng-submit="change_button()">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
      {{ hidden }}
      {% endfor %}
      {% if form.non_field_errors %}
      <div class="form-error">
        {{ form.non_field_errors.0 }}
      </div>
      {% endif %}
      <div class="row inputs">
        <md-input-group>
          <label for="id_username">Username</label>
          <md-input name="username" id="id_username" ng-model="user.username">
        </md-input-group>
        {% if form.username.errors %}
        <span class="error">{{ form.username.errors.0 }}</span>
        {% endif %}
      </div>
      <div class="row inputs">
        <md-input-group>
          <label for="id_password">Password</label>
          <md-input name="password" id="id_password" type="password" ng-model="user.password">
        </md-input-group>
        {% if form.password.errors %}
        <span class="error">{{ form.password.errors.0 }}</span>
        {% endif %}
      </div>
      <div class="row submit">
        <div class="pull-left">
          <md-button class="md-button-raised md-button-colored" type="submit" ng-disabled="sending">
            <i class="fa fa-caret-square-o-right"></i> Login
          </md-button>
        </div>
      </div>
    </form>
    <div class="clearfix"></div>
  </md-card>
</div>
{% endblock %}
{% block js %}
{{ block.super }}

<script>
  ndrive.controller("LoginController", function ($scope) {
    $scope.sending = false;
    $scope.user = {
      username: {% if form.username.value %}"{{ form.username.value|escapejs }}"{% else %}null{% endif %},
      password: null, 
      cont: '{{ form.cont.value }}',
      app_id: '{{ form.app_id.value }}',
    };
    
    $scope.change_button = function () {
      $scope.sending = true;
    };
  });
</script>
{% endblock js %}

server/ndrive/templates/members/paypal-success.html
{% extends "base.html" %}{% load static ndrive %}
{% block title %}PayPal Payment Successful{% endblock %}
{% block content %}
<div id="MembersPage">
  <div layout="horizontal" layout-align="center">
    <md-card class="page">
      <h2>
        Your PayPal Payment was successful!
        <br><br>
        As soon as we receive the funds from PayPal your membership will be activated.
      </h2>
      <md-button href="{% url "members:home" %}" class="md-button-raised md-button-colored">
        Return To Membership &raquo;
      </md-button>
    </md-card>
  </div>
</div>
{% endblock content %}

server/ndrive/templates/members/purchase.html
{% extends "base.html" %}{% load static ndrive %}
{% block title %}{{ level.name }} Membership{% endblock %}
{% block content %}
<div id="MembersPage">
  <div layout="horizontal" layout-align="center">
    <md-card class="page">
      <h2>{{ site_name }} {{ level.name }} Membership</h2>
      <h3>
        ${{ level.cost|dollars }}/year
      </h3>
      <table style="width: auto; border: 0;">
        <tr>
          <td style="border: 0;">
            <form action="{% url 'members:charge' key %}" method="POST">
              {% csrf_token %}
              <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="{{ STRIPE_KEY }}"
                data-image="{% static "img/logo.png" %}"
                data-name="Neutron Drive"
                data-description="{{ level.name }} Membership"
                data-amount="{{ level.cost }}">
              </script>
            </form>
          </td>
          <td style="text-align: center; border: 0;">
            <strong>PayPal</strong>
            {{ paypal_button.render }}
          </td>
        </tr>
      </table>
    </md-card>
  </div>
</div>
{% endblock content %}

server/ndrive/templates/members/support-request.email.html
E-Mail: {{ email }}<br>
Request:<br>
{{ info|linebreaksbr }}

server/ndrive/templates/members/support-success.html
{% extends "base.html" %}{% load static ndrive %}
{% block title %}Support Request{% endblock %}
{% block content %}
<div id="SupportPage">
  <div layout="horizontal" layout-align="center">
    <md-card class="page" ng-controller="FormController">
      <h2>
        We have successfully received your request.<br><br>
        We will contact you shortly.
      </h2>
      <p>
        <md-button href="../">Back to the Members Area &raquo;</md-button>
      </p>
    </md-card>
  </div>
</div>
{% endblock %}

server/ndrive/templates/members/support.html
{% extends "base.html" %}{% load static ndrive %}
{% block title %}Support Request{% endblock %}
{% block content %}
<div id="SupportPage">
  <div layout="horizontal" layout-align="center">
    <md-card class="page" ng-controller="FormController">
      <h2>Submit A Support Request</h2>
      {% include "form.html" %}
    </md-card>
  </div>
</div>
{% endblock %}
{% block js %}
{{ block.super }}

<script>
  {% include "form-controller.js" %}
</script>
{% endblock js %}