server/editor/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns('editor.views',
  url(r'^login/$', 'login_view'),
  url(r'^logout/(.*)$', 'logout_view'),
  
  url(r'^generate-api-key$', 'gen_api_key'),
  url(r'^ekey$', 'ekey'),
  url(r'^get-ekey$', 'get_ekey'),
  
  url(r'^error$', 'report_error'),
  
  url(r'^credits$', 'credits'),
)

server/members/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns('members.views',
  url(r'^$', 'members_home', name="home"),
  url(r'^login/$', 'members_login', name="login"),
  url(r'^cancel/$', 'members_cancel', name="cancel"),
  url(r'^purchase/(\S+)/$', 'purchase', name="purchase"),
  url(r'^charge/(\S+)/$', 'charge', name="charge"),
  url(r'^edit-name/$', 'edit_name', name="edit-name"),
  url(r'^paypal-success/$', 'paypal_success', name="paypal-success"),
  url(r'^support/$', 'support', name="support"),
)

server/ndrive/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('ndrive.views',
  url(r'^grappelli/', include('grappelli.urls')),
  url(r'^admin/', include(admin.site.urls)),
  
  url(r'^editor/', include('editor.urls', namespace='editor', app_name='editor')),
  url(r'^account/', include('account.urls', namespace='account', app_name='account')),
  url(r'^members/', include('members.urls', namespace='members', app_name='members')),
  
  url(r'^paypal-processing/', include('paypal.standard.ipn.urls')),
  
  url(r'^$', 'home'),
  url(r'^favicon.ico$', 'favicon'),
  url(r'^favicon.png$', 'favicon'),
  
  url(r'^help/$', 'page_view', name="help", kwargs={'template': 'pages/help.html'}),
  url(r'^help/neutron-beam-setup$', 'page_view', name="help-nbeam-setup", kwargs={'template': 'pages/help-nbeam-setup.html'}),
  
  url(r'^view-(\d+)$', 'gdrive_webview'),
  url(r'^edit$', 'gdrive_webview'),
)

server/ndrive/views.py
from django import http
from django.conf import settings
from django.template.response import TemplateResponse

def home (request):
  context = {}
  return TemplateResponse(request, 'pages/home.html', context)
  
def favicon (request):
  return http.HttpResponseRedirect('/static/favicon.png')
  
def gdrive_webview (request, index=None):
  if index is None:
    index = request.GET.get('view', '0')
    
  tpl = 'gdrive_webview.html'
  if index == 'test':
    tpl = 'test.html'
    
  return TemplateResponse(
    request,
    tpl,
    {
      'index': index,
      'google_key': settings.GOOGLE_KEY,
      'google_client_id': settings.GOOGLE_CLIENT_ID,
      'google_app_id': settings.GOOGLE_APP_ID,
    }
  )
  
def page_view (request, template=None):
  return TemplateResponse(request, template, {})
  

server/ndrive/templates/base.html
<!DOCTYPE html>{% load static ndrive %}
<html>
  <head>
    <title>{% block title %}The honey badger of code editors{% endblock %} | {{ site_name }}</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static "bower_components/angular-material/angular-material.min.css" %}">
    <link rel="stylesheet" href="{% static "bower_components/font-awesome/css/font-awesome.min.css" %}">
    {% if DEV %}
    <link rel="stylesheet/less" type="text/css" href="{% static "css/main.less" %}">
    <script src="{% static "js/less.js" %}" type="text/javascript"></script>
    {% else %}
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    {% endif %}
    
    <link href='https://fonts.googleapis.com/css?family=VT323' rel='stylesheet' type='text/css'>
    <base href="/">
  </head>
  <body ng-app="ndrive" ng-keydown="easter_egg($event)">
    <div layout="vertical" layout-fill>
    <md-toolbar>
      <div class="md-toolbar-tools">
        <span class="site-name">
          <a href="/"{% target %}><img src="{% static "img/logo.png" %}"></a>
        </span>
        <span class="site-name">
          <a href="/" {% target %}>{{ site_name }}</a>
        </span>
        <span class="menu" flex>
          <ul ng-class="{mon: menu_on}">
            <li class="mobile">
              <a ng-click="toggle_menu()" class="btn"><i class="fa fa-bars"></i></a>
            </li>
            <li>
              <a href="https://chrome.google.com/webstore/detail/super-neutron-drive/hjmodhnpiombojkgckmmhjhihfhphajp">Install</a>
            </li>
            <li>
              <a href="http://blog.neutrondrive.com/">Blog</a>
            </li>
            <li>
              <a href="http://neutron.spreadshirt.com/">Shop</a>
            </li>
            <li>
              <a href="{% url "members:home" %}">Members</a>
            </li>
            <li>
              <a href="/help/">Help</a>
            </li>
          </ul>
        </span>
      </div>
    </md-toolbar>
    <md-content>
      {% block content %}
      {% endblock content %}
    </md-content>
  </div>
    {% block js %}
    <script src="{% static "bower_components/angular/angular.min.js" %}"></script>
    <script src="{% static "bower_components/angular-aria/angular-aria.min.js" %}"></script>
    <script src="{% static "bower_components/angular-animate/angular-animate.min.js" %}"></script>
    <script src="{% static "bower_components/hammerjs/hammer.min.js" %}"></script>
    <script src="{% static "bower_components/angular-material/angular-material.min.js" %}"></script>
    
    <script src="{% static "js/ng/app.js" %}"></script>
    {% endblock js %}
  </body>
</html>

server/ndrive/templates/email.base.html
<!DOCTYPE html>{% load static %}
<html>
  <head>
    <title>{{ site_name }}</title>
  </head>
  <body>
    <table cellspacing="0" border="0" cellpadding="0" style="border: 0; border-collapse: collapse; max-width: 550px; margin: 0 auto;">
      <tr>
        <td style="background-color: {{ style.headerBg }}; padding: 20px;">
          <table style="border: 0; border-collapse: collapse;" cellspacing="0" border="0" cellpadding="0">
            <td style="vertical-align: middle; text-align: left; padding: 0 10px 0 0;">
              <img src="{{ abs_base_url }}{% static "img/logo.png" %}" alt="{{ site_name }}" style="width: 48px;">
            </td>
            <td style="vertical-align: middle; text-align: left; padding: 0; font-weight: bold; font-size: 150%;">
              {{ site_name }}
            </td>
          </table>
        </td>
      </tr>
      <tr>
        <td style="padding: 20px;">
          {% block content %}{% endblock %}
        </td>
      </tr>
    </table>
  </body>
</html>

server/ndrive/templates/form.html
<form action="{{ request.path }}" method="post">{% load ndrive %}
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
  {{ hidden }}
  {% endfor %}
  {% if form.non_field_errors %}
  <div class="form-error">
    {{ form.non_field_errors.0 }}
  </div>
  {% endif %}
  {% for field in form.visible_fields %}
  {% if field|isCheckbox %}
  <div class="row">
    <md-checkbox ng-model="form.{{ field.name }}" aria-label="{{ field.label }}">
      {{ field.label }}
    </md-checkbox>
    <input type="checkbox" name="{{ field.name }}" ng-model="form.{{ field.name }}" class="hidden">
  </div>
  {% else %}
  <div class="row inputs">
    <md-input-group>
      <label for="id_{{ field.name }}">{{ field.label }}{% if field.field.required %}<sup>(required)</sup>{% endif %}</label>
      {% if field|isTextArea %}
      <br>
      <textarea name="{{ field.name }}" id="id_{{ field.name }}" ng-model="form.{{ field.name }}"></textarea>
      {% else %}
      <md-input name="{{ field.name }}" id="id_{{ field.name }}" ng-model="form.{{ field.name }}" type="{{ field.field.widget.input_type }}">
      {% endif %}
    </md-input-group>
    {% if field.errors %}
    <span class="error">{{ field.errors.0 }}</span>
    {% endif %}
  </div>
  {% endif %}
  {% endfor %}
  <div class="row submit">
    <div>
      <md-button class="md-button-raised md-button-colored" type="submit">
        <i class="fa fa-{{ icon }}"></i> {{ action }}
      </md-button>
    </div>
  </div>
</form>

server/ndrive/templates/gdrive_webview.html
<!DOCTYPE html>
<html>
  <head>
    <title>Super Neutron Drive</title>
    <meta charset="utf-8">
    <link href='//fonts.googleapis.com/css?family=VT323|Open+Sans' rel='stylesheet' type='text/css'>
    <style>
      body {
        font-family: 'Open Sans', sans-serif;
        text-align: center;
        margin: 20px;
        padding: 0;
      }
      
      h1 {
        font-family: 'VT323';
        font-size: 60px;
        font-weight: normal;
      }
    </style>
  </head>
  <body>
    <div id="email"></div>
    <img src="/static/img/logo.png" alt="">
    <h1>Super Neutron Drive</h1>
    <h2>Google Service</h2>
    <h3 id="sharing-btn" style="display: none;">
      <a href="javascript: void(0);" onclick="Drive.done_sharing()" style="text-decoration: none;">&laquo; Done Sharing &raquo;</a>
    </h3>
    <script>
      var GOOGLE_KEY = '{{ google_key }}';
      var GOOGLE_CLIENT_ID = '{{ google_client_id }}';
      var GOOGLE_APP_ID = '{{ google_app_id }}';
    </script>
    
    <script src="/static/js/neutron.js?ds={% now "YmdHis" %}"></script>
    <script src="/static/js/drive.js?ds={% now "YmdHis" %}"></script>
    
    <script src="https://www.google.com/jsapi"></script>
    <script src="https://apis.google.com/js/api.js"></script>
    <script src="https://apis.google.com/js/client.js"></script>
  </body>
</html>

server/ndrive/templates/message.html
{% extends "base.html" %}{% load static %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div layout="horizontal" layout-align="center">
  <md-card>
    <h2>{{ message|safe }}</h2>
    {% if submessage %}
    <h3>{{ submessage }}</h3>
    {% endif %}
    <img src="{% static "img/logo.png" %}" alt="" style="display: block; margin: 0 auto;">
  </md-card>
</div>
{% endblock content %}

server/ndrive/templates/test.html
<!DOCTYPE html>
<html>
  <head>
    <title>Super Neutron Drive</title>
    <meta charset="utf-8">
    <link href='//fonts.googleapis.com/css?family=VT323|Open+Sans' rel='stylesheet' type='text/css'>
    <style>
      body {
        font-family: 'Open Sans', sans-serif;
        text-align: center;
        margin: 20px;
        padding: 0;
      }
      
      h1 {
        font-family: 'VT323';
        font-size: 60px;
        font-weight: normal;
      }
    </style>
  </head>
  <body>
    <div id="email"></div>
    <img src="/static/img/logo.png" alt="">
    <h1>Super Neutron Drive</h1>
    <h2>Google Service</h2>
    <h3 id="sharing-btn" style="display: none;">
      <a href="javascript: void(0);" onclick="Drive.done_sharing()" style="text-decoration: none;">&laquo; Done Sharing &raquo;</a>
    </h3>
    
    <button onclick="do_share()">Share</button>
    <script>
      var GOOGLE_KEY = '{{ google_key }}';
      var GOOGLE_CLIENT_ID = '{{ google_client_id }}';
      var GOOGLE_APP_ID = '{{ google_app_id }}';
    </script>
    
    
    <script src="https://www.google.com/jsapi"></script>
    <script src="https://apis.google.com/js/api.js"></script>
    <script src="https://apis.google.com/js/client.js"></script>
    <script>
var immediateAuth = false;
var Neutron = {
  gdrive_api_loaded: false,
  authorized: false,
  authorizer: null,
  OAuth: null,
  UserId: null,
  parent: null,
  origin: null,
  id: null,
  init_token: null,
  share: null
};

function start () {
          gapi.load('auth:client,drive-realtime,drive-share,picker', function () {
            Neutron.auth_init(true);
          });

}

function do_share () {
  file_id = prompt('file id:');
  s = new gapi.drive.share.ShareClient(GOOGLE_APP_ID);
  s.setItemIds([file_id]);
  s.showSettingsDialog();
}

Neutron.auth_init = function (setkey, force_slow) {
  console.log('narf');
  if (setkey) {
    gapi.client.setApiKey(GOOGLE_KEY);
  }
  
  if (!Neutron.share) {

  }
    
  if (!Neutron.gdrive_api_loaded) {
    gapi.client.load('drive', 'v2', function () {
      Neutron.gdrive_api_loaded = true;
      Neutron.auth_init();
    });
    return 0;
  }
  
  if (Neutron.authorizer) {
    clearTimeout(Neutron.authorizer);
    Neutron.authorizer = null;
  }
  
  var options = {
    client_id: GOOGLE_CLIENT_ID,
    immediate: false,
    scope: [
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/drive.scripts',
      'https://www.googleapis.com/auth/userinfo.profile',
      'https://www.googleapis.com/auth/drive.install',
      'https://www.googleapis.com/auth/drive.file'
    ]
  };
  
  if (Neutron.UserId) {
    options.user_id = Neutron.UserId;
  }
  
  if (force_slow) {
    options.immediate = false;
  }
  
  gapi.auth.authorize(options, Neutron.auth_callback);
};

Neutron.auth_callback = function (OAuth) {  

  console.log('callback');
  if (OAuth && OAuth.error) {
    Neutron.auth_init(false, true);
    return null;
  }
  
  if (OAuth && OAuth.expires_in) {
    try {
      gapi.drive.realtime.setServerAddress('https://docs.google.com/otservice/');
    }
    
    catch (e) {
      setTimeout(Neutron.auth_init, 300);
      return 0;
    }
    
    Neutron.OAuth = OAuth;
    Neutron.authorizer = setTimeout(Neutron.auth_init, 60 * 25 * 1000);
    Neutron.authorized = true;
    
    oauth = {
      access_token: OAuth.access_token,
      expires_at: OAuth.expires_at
    };
    
    gapi.client.load('oauth2', 'v2', function() {
      gapi.client.oauth2.userinfo.get().execute(function (resp) {
        oauth.user_id = resp.id;
        Neutron.UserId = resp.id;
        
        var request = gapi.client.drive.about.get();
        request.execute(function (response) {
          document.querySelector("#email").innerHTML = 'Account: ' + response.user.emailAddress;
          immediateAuth = true;
        });
      });
    });
  }
};

Neutron.pick_folder = function () {
  var docsView = new google.picker.DocsView().
    setIncludeFolders(true).
    setMimeTypes('application/vnd.google-apps.folder').
    setSelectFolderEnabled(true);
  var picker = new google.picker.PickerBuilder().
    addView(docsView).
    setOAuthToken(Neutron.OAuth.access_token).
    setDeveloperKey(GOOGLE_KEY).
    setCallback(Neutron.pick_folder_callback).
    build();
  picker.setVisible(true);
};

Neutron.pick_folder_callback = function (data) {
  if (data[google.picker.Response.ACTION] == google.picker.Action.PICKED) {
    var doc = data[google.picker.Response.DOCUMENTS][0];
    var id = doc[google.picker.Document.ID];
    console.log(id);
  }
  
  else if (data[google.picker.Response.ACTION] == google.picker.Action.CANCEL) {
    console.log('cancel');
  }
};


window.onload = start;
    </script>
  </body>
</html>